[package]
name = "iota-stronghold"
version = "0.1.0"
authors = ["tensorprogramming <tensordeveloper@gmail.com>", "Daniel Thompson-Yvetot <daniel.yvetot@iota.org>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "Client interface for Stronghold"
keywords = ["iota", "stronghold", "security"]
categories = [ "security" ]
homepage = "https://iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[dependencies]
stronghold-engine = {path = "../engine"}

bincode = "1.3"
serde = {version = "1.0", features = ["derive"]}
zeroize = "1.1"
zeroize_derive = "1.0"
anyhow = "1.0"
thiserror = "1.0"
futures = "0.3"

riker = "0.4"

stronghold-runtime = {path = "../runtime"}

[dependencies.iota-crypto]
git = "https://github.com/iotaledger/crypto.rs"
rev = "cf6b842d33926ed0a5b177e7b079c03d8804be09"
features = [ "ed25519", "sha", "hmac", "bip39" ]

[dev-dependencies]
hex = "0.4.2"

[workspace]
