[package]
name = "stronghold-runtime"
version = "0.2.0"
edition = "2021"
readme = "README.md"

[lib]
name = "runtime"

[dependencies]
zeroize = { version = "1.4.3" }
libsodium-sys = { version = "0.2" }
serde = { version = "1.0", features = [ "derive" ] }
random = { version = "0.8.4", package = "rand" }
dirs = { version = "4.0.0" }
thiserror = { version = "1.0" }
iota-crypto = { version = "0.8.0", features = [ "blake2b" ] }

[dev-dependencies]
serde_json = { version = "1.0" }
