[package]
name                    = "stronghold-runtime"
version                 = "0.1.0"
edition                 = "2021"
readme                  = "README.md"

[lib]
name                    = "runtime"
 
[dependencies]
zeroize                 = { version = "1.4.3" }
libsodium-sys           = { version = "0.2" }
serde                   = { version = "1.0", features = [ "derive" ] }
random                  = { version = "0.8.4", package = "rand" }
dirs                    = { version = "4.0.0" }
thiserror               = { version = "1.0" }
iota-crypto             = { version = "0.8.0", features = ["sha"] }

# experimental dependencies for fragmenting allocator
libc                    = { version = "0.2" }

[dev-dependencies]
serde_json              = { version = "1.0" }