[package]
name = "stronghold-utils"
version = "0.2.1"
authors = [
  "IOTA Stiftung",
  "tensor-programming <tensordeveloper@gmail.com>"
]
edition = "2018"
license = "Apache-2.0"

[dependencies]
futures = "0.3"
rand = "0.8.3"
riker = "0.4"

  [dependencies.utils-derive]
  path = "../utils-derive"
  version = "0.1.1"
