[package]
name = "stronghold-engine"
version = "0.3.1"
authors = [
  "IOTA Stiftung",
  "tensorprogramming <tensordeveloper@gmail.com>"
]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
keywords = [ "iota", "stronghold", "cryptography", "security" ]
categories = [ "security" ]
description = "A rust implementation of the IOTA Stronghold low-level libraries"
homepage = "https://stronghold.docs.iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[lib]
name = "engine"

[dependencies.vault]
path = "vault"
version = "0.3"

[dependencies.snapshot]
path = "snapshot"
version = "0.3"

[dependencies.store]
path = "store"
version = "0.3"

[dependencies.runtime]
path = "runtime"
version = "0.3"
