[package]
name = "stronghold-engine"
version = "0.2.0"
authors = [ "tensorprogramming <tensordeveloper@gmail.com>" ]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
keywords = [ "iota", "stronghold", "cryptography", "security" ]
categories = [ "security" ]
description = "A rust implementation of the IOTA Stronghold low-level libraries"
homepage = "https://iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[lib]
name = "engine"

[dependencies.crypto]
path = "crypto"
version = "0.2"

[dependencies.vault]
path = "vault"
version = "0.2"

[dependencies.primitives]
path = "primitives"
version = "0.2"

[dependencies.random]
path = "random"
version = "0.2"

[dependencies.snapshot]
path = "snapshot"
version = "0.2"

[dependencies.store]
path = "store"
version = "0.2"

[dependencies.secret]
path = "secret"
version = "0.1"
