[package]
name = "stronghold-runtime"
version = "0.1.0"
authors = ["Gustav Behm <gustav.behm@iota.org>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
keywords = ["iota", "stronghold", "security"]
categories = [ "security" ]
homepage = "https://iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[lib]
name = "runtime"

[dependencies]
libc = "0.2.79"
memoffset = "0.6.1"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies.num]
version = "0.3.0"
default-features = false

[build-dependencies]
bindgen = "0.55.1"

[dev-dependencies]
rand = "0.7.3"
