[package]
name = "commandline"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.0-beta.1", features = ["yaml"] }

iota-parti = {path = "../../"}

bincode = "1.3.1"
serde = {version = "1.0.114", features = ["derive"]}

[[bin]]
name = "stronghold"
path = "src/main.rs"

[workspace]
