name: Release Stronghold CLI

on:
  workflow_dispatch:
  push:
    branches:
      - ci/cli-release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: products/commandline

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install gon (macOS)
      # https://github.com/mitchellh/gon
      run: brew install mitchellh/gon/gon
      if: matrix.os == 'macos-latest'

    # - name: Get current date
    #   if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
    #   run: echo "::set-env name=CURRENT_DATE::$(date +'%Y-%m-%d')"

    # - name: Get current date
    #   if: matrix.os == 'windows-latest'
    #   run: echo "::set-env name=CURRENT_DATE::$(Get-Date -Format "yyyy-MM-dd")"

    # - name: Cache cargo registry
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cargo/registry
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

    # - name: Cache cargo index
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cargo/git
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}

    # - name: Cache cargo target
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ matrix.project}}/target
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Build Stronghold CLI
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=products/commandline/Cargo.toml --release
    
    - name: Import code signing assets (macOS)
      # Based on https://github.com/Apple-Actions/import-codesign-certs/blob/master/src/security.ts
      run: |
        security create-keychain -p $KEYCHAIN_PASSWORD signing.keychain
        security set-keychain-settings -lut 3600 signing.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD signing.keychain
        echo $MAC_CERT_BASE64 | base64 -D -o signing.p12
        security import signing.p12 -k signing.keychain -f pkcs12 -T "/usr/bin/codesign" -T "/usr/bin/security" -P $MAC_CERT_PASSWORD
        rm signing.p12
        security -q set-key-partition-list -S apple-tool:,apple: -k $KEYCHAIN_PASSWORD signing.keychain > /dev/null
        security -v list-keychains -s signing.keychain
        security find-identity -vp codesigning
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
        MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
      if: matrix.os == 'macos-latest'

    - name: Sign and notarize Stronghold CLI binary (macOS)
      run: gon gon-config.json
      env:
        AC_USERNAME: ${{ secrets.ASC_APPLE_ID }}
        AC_PASSWORD: ${{ secrets.ASC_PASSWORD }}
      if: matrix.os == 'macos-latest'
    
    - name: Delete keychain (macOS)
      run: security delete-keychain signing.keychain
      # Run even if previous steps fail
      if: ${{ matrix.os == 'macos-latest' && always() }}

    - name: Upload artifacts (Windows/Linux)
      uses: actions/upload-artifact@v2
      with:
        name: stronghold-cli-${{ matrix.os }}
        path: |
          products/commandline/target/release/stronghold
          products/commandline/target/release/stronghold.exe
      if: matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest'
    
    - name: Upload artifacts (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: stronghold-cli-${{ matrix.os }}
        path: products/commandline/stronghold.zip
      if: matrix.os == 'macos-latest'
